#!/usr/bin/env bash

query=$(rofi -dmenu -p "Search")

# Exit if empty
[ -z "$query" ] && exit

# Encode spaces
url="https://www.google.com/search?q=$(printf '%s' "$query" | sed 's/ /+/g')"

# Detect active window class
active_class=$(hyprctl activewindow -j | jq -r '.class')

if [ "$active_class" = "firefox" ]; then
    # Open new tab in existing Firefox
    firefox --new-tab "$url"
else
    # Open new window
    firefox --new-window "$url"
fi
